<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="6825" started-at="2019-09-28T17:22:39 CST" finished-at="2019-09-28T17:22:46 CST">
    <groups>
      <group name="home">
        <method signature="homeTest.test()[pri:0, instance:com.bx.testng.homeTest@6cc4c815]" name="test" class="com.bx.testng.homeTest"/>
      </group> <!-- home -->
    </groups>
    <test name="Command line test" duration-ms="6825" started-at="2019-09-28T17:22:39 CST" finished-at="2019-09-28T17:22:46 CST">
      <class name="com.bx.testng.LoginTest">
        <test-method status="FAIL" signature="home(java.lang.String, java.lang.String)[pri:0, instance:com.bx.testng.LoginTest@3a82f6ef]" name="home" duration-ms="3452" started-at="2019-09-28T17:22:41 CST" data-provider="user" finished-at="2019-09-28T17:22:44 CST">
          <params>
            <param index="0">
              <value>
                <![CDATA[1310831029@qq.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456bx]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[登录成功跳转首页失败！ expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 登录成功跳转首页失败！ expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at com.bx.testng.LoginTest.home(LoginTest.java:69)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:62)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:141)
at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:338)
at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:997)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- home -->
        <test-method status="PASS" signature="test(java.lang.String, java.lang.String)[pri:0, instance:com.bx.testng.LoginTest@3a82f6ef]" name="test" duration-ms="1164" started-at="2019-09-28T17:22:44 CST" data-provider="user" finished-at="2019-09-28T17:22:46 CST">
          <params>
            <param index="0">
              <value>
                <![CDATA[1310831029@qq.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456bx]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- com.bx.testng.LoginTest -->
      <class name="com.bx.testng.homeTest">
        <test-method status="PASS" signature="test()[pri:0, instance:com.bx.testng.homeTest@6cc4c815]" name="test" duration-ms="1486" started-at="2019-09-28T17:22:39 CST" finished-at="2019-09-28T17:22:40 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- com.bx.testng.homeTest -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
